image: node

stages:
  - lint
  - unit-test

lint:
  stage: lint
  script:
    - cd resilience-indicator-backend && npm_config_loglevel=silent npm i eslint
    - node_modules/eslint/bin/eslint.js .
    - cd ../resilience-indicator && npm_config_loglevel=silent npm i eslint
    - node_modules/eslint/bin/eslint.js .

unit-test:
  stage: unit-test
  services:
    - mysql:5.7.24
  variables:
    # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
    # MYSQL_DATABASE: $MYSQL_DATABASE
    # MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    MYSQL_DATABASE: "inl_db"
    MYSQL_ROOT_PASSWORD: "pass"
  script:
    - cd resilience-indicator-backend
    - npm_config_loglevel=silent npm i -g sequelize-cli
    - npm_config_loglevel=silent npm i sequelize
    - export DB_ENV=ci
    - (cd src/ && sequelize db:create --env test && sequelize db:migrate --env test && sequelize db:seed:all --env test)
    - npm_config_loglevel=silent npm i jest
    - node_modules/jest/bin/jest.js .
